(progn ; for stupid ## thing
  (defpackage "DWF"
    (:use "CL" "CFFI")
    (:export "DWF-ERROR")
    ;; devices.lisp
    (:export "DEVICE" "DEVICE-TYPE" "DEVICE-VERSION" "DEVICE-SERIAL"
	     "DEVICE-HANDLE" "DEVICE-FROM-ID" "DEVICES"
	     "DEVICE-CONNECTED-P" "DEVICE-CONNECT" "DEVICE-DISCONNECT")
    ;; the C API (DWF-C for raw versions, so to speak)
    #1=(:export "GET-LAST-ERROR" "GET-LAST-ERROR-MSG" "GET-VERSION"
		"ENUM" "ENUM-DEVICE-TYPE" "ENUM-DEVICE-IS-OPENED"
		"ENUM-USER-NAME" "ENUM-DEVICE-NAME" "ENUM-SN"
		"DEVICE-OPEN" "DEVICE-CLOSE" "DEVICE-CLOSE-ALL"
		"DEVICE-AUTO-CONFIGURE-SET" "DEVICE-TRIGGER-INFO"
		"ANALOG-OUT-RESET" "ANALOG-OUT-CONFIGURE"
		"ANALOG-OUT-STATUS" "ANALOG-OUT-NODE-PLAY-STATUS"
		"ANALOG-OUT-NODE-PLAY-DATA"
		"ANALOG-OUT-COUNT"
		"ANALOG-OUT-NODE-DATA-SET"
		"ANALOG-IN-RESET" "ANALOG-IN-CONFIGURE"
		"ANALOG-IN-STATUS" "ANALOG-IN-STATUS-SAMPLES-LEFT"
		"ANALOG-IN-STATUS-SAMPLES-VALID"
		"ANALOG-IN-STATUS-INDEX-WRITE"
		"ANALOG-IN-STATUS-AUTO-TRIGGERED"
		"ANALOG-IN-STATUS-DATA" "ANALOG-IN-STATUS-SAMPLE"
		"ANALOG-IN-STATUS-RECORD"
		"ANALOG-IN-STATUS-RECORD-LENGTH-SET"
		"ANALOG-IN-STATUS-RECORD-LENGTH-GET"
		"ANALOG-IN-FREQUENCY-INFO" "ANALOG-IN-FREQUENCY-SET"
		"ANALOG-IN-FREQUENCY-GET" "ANALOG-IN-BITS-INFO"
		"ANALOG-IN-BUFFER-SIZE-INFO"
		"ANALOG-IN-BUFFER-SIZE-SET"
		"ANALOG-IN-BUFFER-SIZE-GET"
		"ANALOG-IN-ACQUISITION-MODE-INFO"
		"ANALOG-IN-ACQUISITION-MODE-SET"
		"ANALOG-IN-ACQUISITION-MODE-GET"
		"ANALOG-IN-CHANNEL-COUNT"
		"ANALOG-IN-CHANNEL-ENABLE-SET"
		"ANALOG-IN-CHANNEL-ENABLE-GET"
		"ANALOG-IN-CHANNEL-FILTER-INFO"
		"ANALOG-IN-CHANNEL-FILTER-SET"
		"ANALOG-IN-CHANNEL-FILTER-GET"
		"ANALOG-IN-CHANNEL-RANGE-SET"
		"ANALOG-IN-CHANNEL-RANGE-GET"
		"ANALOG-IN-CHANNEL-OFFSET-SET"
		"ANALOG-IN-CHANNEL-OFFSET-GET"))
  (defpackage "DWF-C"
    (:use)
    #1#))
